#!/usr/bin/env python3
"""
gRPC Servicer for Quickbooks Online Mcp Server

Auto-generated by doc2db-integrate v2 (Phase 10).
Implements the QuickbooksOnlineMcpServerService with 0 RPC handler(s).

Usage:
    python quickbooks_online_mcp_server_servicer.py
"""
import os
import subprocess
from concurrent import futures
from pathlib import Path

import grpc

# These are generated by protoc from quickbooks_online_mcp_server.proto
import quickbooks_online_mcp_server_pb2
import quickbooks_online_mcp_server_pb2_grpc

APP_DIR = Path(__file__).parent
DEFAULT_PORT = 50051


class QuickbooksOnlineMcpServerServicer(quickbooks_online_mcp_server_pb2_grpc.QuickbooksOnlineMcpServerServiceServicer):
    """Implements the QuickbooksOnlineMcpServerService gRPC interface."""

    def Health(self, request, context):
        """Health check."""
        return quickbooks_online_mcp_server_pb2.HealthResponse(
            status="ok",
            app_id="quickbooks-online-mcp-server",
        )


def serve(port: int = DEFAULT_PORT):
    """Start the gRPC server."""
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=4))
    quickbooks_online_mcp_server_pb2_grpc.add_QuickbooksOnlineMcpServerServiceServicer_to_server(
        QuickbooksOnlineMcpServerServicer(), server
    )
    server.add_insecure_port(f"[::]:{{port}}")
    server.start()
    print(f"gRPC server for Quickbooks Online Mcp Server listening on port {{port}}")
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
